"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(3, 5);
console.log("Coordenada X:", myPoint.getX());
console.log("Coordenada Y:", myPoint.getY());
myPoint.setX(10);
myPoint.setY(8);
console.log("Nuevas coordenadas:", myPoint.toString());
var point1 = new point_1.Point(3, 4);
var point2 = new point_1.Point(6, 8);
console.log("Distancia al origen para point1:", point1.distanceToOrigin());
console.log("Distancia al origen para point2:", point2.distanceToOrigin());
console.log("Distancia entre point1 y point2:", point1.calculateDistance(point2));
