"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var triangle_1 = require("./triangle");
var Point_1 = require("./Point");
var vertex1 = new Point_1.Point(0, 0);
var vertex2 = new Point_1.Point(3, 0);
var vertex3 = new Point_1.Point(0, 4);
var myTriangle = new triangle_1.Triangle(vertex1, vertex2, vertex3);
var sidesLength = myTriangle.calculateLengthSides();
console.log("Longitud de los lados del triángulo son:", sidesLength);
